version: '3.9'

services:
  client:
    container_name: client
    image: client
    build:
      context: ./client
      dockerfile: client.dockerfile
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - server
  server:
    container_name: server
    image: server
    build:
      context: ./server
      dockerfile: server.dockerfile
    ports:
      - 8080:8080
  db:
    container_name: db
    image: redis
    build:
      context: .
      dockerfile: db.dockerfile
    restart: always
    ports:
      - 6380:6379